---
title: "Member versus Casual"
date:  "2022-12-2"
author: "Joseph White"
output: html_notebook
---

This notebooks will try to use the `lehdr` package to get at detailed demographic data

## Install lehdr
Run this code only once.
```{r}
#devtools::install_github("jamgreen/lehdr")
```

## Packages
```{r}
library(knitr)
library(tidyverse)
library(janitor)
library(lubridate) # because we will probably see some dates
library(here) # a package I haven't taught you about before that doesn't do much, but ....
library(sf) # working with simple features - geospatial
library(tmap)
library(tidycensus)
library(lehdr)
library(rnaturalearth)
library(WDI)
library(tigris)
library(rgdal)
library(sp)
```

## read spacial data
```{r}
neigh=st_read(here("DC_Health_Planning_Neighborhoods_joey.geojson")) %>% clean_names()
class(neigh)
```

## loading census data
```{r}
census_api_key("d44395e2fa101f82260fae6b845676d71f017b70")

#what variables
v20 = load_variables(2018,"acs5")
# median_family_income="	B06011_001" 
# all "B00001_001"	
#black "B02009_001"
#---------------------------------------------------------------
df_cencus=get_acs(geography = "tract",
                  variables=c("median_inc"="B06011_001",
                              "pop"="B01001_001",
                              "pop_black"="B02009_001"),
                  state="DC",geometry=TRUE,year=2018) 
#---------------------------------------------------------------
df_cens=df_cencus %>% select(-moe) %>% spread(variable,estimate)
df_cens_adj=df_cens %>% st_transform(4326)
#---------------------------------------------------------------
df_j=st_join(df_cens_adj,neigh,largest=TRUE)
#---------------------------------------------------------------
df1=df_j %>% select(median_inc,pop,pop_black,objectid) %>%
  group_by(objectid) %>%
  summarise(pop_n=sum(pop),
            pop_black_n=sum(pop_black), 
            adj_median_income=sum(pop*median_inc)/pop_n) 
#---------------------------------------------------------------
df2=left_join(neigh2,df1 %>% st_set_geometry(NULL))
```

## Bike Data
```{r}
bike_data <- read_csv("202209-capitalbikeshare-tripdata.csv") %>% clean_names()
#---------------------------------------------------------------
bike_data_sf <- bike_data %>%
  mutate_at(vars(start_lat, start_lng), as.numeric) %>%
  st_as_sf(
    coords = c("start_lat", "start_lng"), 
    agr = "constant",
    crs = "4326"
  ) %>%
  sample_n(1000)
#---------------------------------------------------------------
st_crs(bike_data_sf) <- 4326
```
```{r}
bike_data_sf_1 <- bike_data_sf %>%
  select(geometry) %>%
  rename(geom_points = geometry)

neigh_1 <- neigh %>%
  select(geometry)

df_full = st_join(bike_data_sf_1, neigh_1, join = st_within)
```

