---
title: "Class Project"
date:  "2022-11-29"
author: "Nate Smullen, Alex Lindquist, Wynter Malone"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyverse)
library(here)
library(janitor)
library(gbfs)
library(taskscheduleR) #might be useful for running code every minute
```


```{r}
#Code that runs about every minute to grab station info on chosen variables.
i = 0
filename= "U:/DS241-Class-Project/analysis/station_info.csv"

headers = data.frame("station_id", "num_docks_available", "num_docks_disabled", "num_bikes_available",
            "num_ebikes_available", "num_bikes_disabled", "total_bikes_available")
write.table(headers, file = filename, append=TRUE, row.names = FALSE,
            col.names = FALSE, sep = ",")

while(i < 60) {
  print(paste("its been", i, "minutes since this started, give or take a bit"))
  i = i + 1
  
  station_status <- get_station_status("cabi") %>%
            select(station_id, num_docks_available, num_docks_disabled,
            num_bikes_available, num_ebikes_available, num_bikes_disabled) %>%
        mutate(total_bikes_available = num_bikes_available + num_docks_available  
            + num_ebikes_available - num_docks_disabled - num_bikes_disabled )


write.table(station_status, file=filename, append=TRUE, row.names = FALSE,
            col.names = FALSE, sep = ",")


  Sys.sleep(60)
}
```

```{r}
thisfile=here("analysis" ,"station_info.csv")

df1 = read_csv(thisfile) %>% clean_names()
```


