---
title: "Class Project"
date:  "2022-11-29"
author: "Nate Smullen"
output: html_notebook
---

```{r}
library(lehdr)
library(dplyr)
library(stringr)

library(tidyverse)
library(here)
library(janitor)
library(maps)
library(lubridate)
library(gbfs)

library(taskscheduleR) #might be useful for running code every minute
```

```{r}
dc_od <- grab_lodes(state = "dc", year = 2019, lodes_type = "od", job_type = "JT01", 
           segment = "S000", state_part = "main", agg_geo = "tract")
```

```{r}
dc_rac <- grab_lodes(state = "dc", year = 2019, lodes_type = "rac", 
                     job_type = "JT01", segment = "S000", agg_geo = "tract")
```

```{r}
dc_wac <- grab_lodes(state = "dc", year = 2019, lodes_type = "wac", 
                     job_type = "JT01", segment = "S000", agg_geo = "tract")
```

```{r}
station_status <- get_station_status("cabi") %>% 
  select(station_id, num_docks_available, num_docks_disabled, 
         num_bikes_available, num_ebikes_available, num_bikes_disabled) %>%
  mutate(total_bikes_available = 
  num_bikes_available + num_docks_available + num_ebikes_available)
```

```{r}
#code that runs every minute for an hour
#problem with this code is that it doesn't account for the time it takes to do
#The calculation
i = 0
while(i < 60) {
  print(paste("its been", i, "minutes since this started, give or take a bit"))
  i = i + 1
  
  Sys.sleep(60)
}
```

```{r}
filename= "U:/DS241-Class-Project/analysis/test.csv"
headers = data.frame("station_id", "num_docks_available", "num_docks_disabled", "num_bikes_available",
            "num_ebikes_available", "num_bikes_disabled", "total_bikes_available")

write.table(headers, file = filename, append=TRUE, row.names = FALSE,
            col.names = FALSE, sep = ",")
```

```{r}
thisfile=here("analysis" ,"test.csv")

test = read_csv(thisfile) %>% clean_names()
```

